version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: novarix_db
      POSTGRES_USER: novarix_db_user
      POSTGRES_PASSWORD: dein_passwort
    ports:
      - "5432:5432"
